export const ACTION_TYPES = {
  PLAYERS_FETCH_INIT: "PLAYERS_FETCH_INIT",
  PLAYERS_FETCH_SUCCESS: "PLAYERS_FETCH_SUCCESS",
  PLAYERS_FETCH_FAILURE: "PLAYERS_FETCH_FAILURE",

  PLAYERS_SHUFFLE_INIT: "PLAYERS_SHUFFLE_INIT",
  PLAYERS_SHUFFLE_SUCCESS: "PLAYERS_SHUFFLE_SUCCESS",
  PLAYERS_SHUFFLE_FAILURE: "PLAYERS_SHUFFLE_FAILURE",
};
